import {
  GaugeIcon,
  HouseIcon,
  DatabaseIcon,
  UsersIcon,
  ShieldIcon,
  ShieldCheckIcon,
  SquaresFourIcon,
  ListChecksIcon,
  KeyIcon,
  SlidersHorizontalIcon,
  LightningIcon,
  BuildingsIcon,
  MoneyIcon,
  CalendarBlankIcon,
  StethoscopeIcon,
  BoatIcon,
  LineSegmentsIcon,
  UserListIcon,
  UserSquareIcon,
  StackSimpleIcon,
  PawPrintIcon,
  FileArchiveIcon,
  UserIcon,
  ListIcon,
  ListBulletsIcon,
  PathIcon,
  ClockCounterClockwiseIcon,
  FilesIcon,
  FileTextIcon,
  type Icon,
} from "@phosphor-icons/react";

export const iconMap: Record<string, Icon> = {
  LayoutDashboard: GaugeIcon,
  House: HouseIcon,
  Database: DatabaseIcon,
  Users: UsersIcon,
  Shield: ShieldIcon,
  ShieldCheck: ShieldCheckIcon,
  SquaresFour: SquaresFourIcon,
  ListChecks: ListChecksIcon,
  KeyRound: KeyIcon,
  SlidersHorizontal: SlidersHorizontalIcon,
  Bolt: LightningIcon,
  Buildings: BuildingsIcon,
  Money: MoneyIcon,
  CalendarBlank: CalendarBlankIcon,
  Stethoscope: StethoscopeIcon,
  Boat: BoatIcon,
  LineSegments: LineSegmentsIcon,
  UserList: UserListIcon,
  UserSquare: UserSquareIcon,
  StackSimple: StackSimpleIcon,
  PawPrint: PawPrintIcon,
  FileArchive: FileArchiveIcon,
  User: UserIcon,
  List: ListIcon,
  ListBullets: ListBulletsIcon,
  Path: PathIcon,
  Files: FilesIcon,
  FileText: FileTextIcon,
  ClockCounterClockwise: ClockCounterClockwiseIcon,
};

export const iconOptions = Object.keys(iconMap).map((key) => ({
  label: key,
  value: key,
}));
