sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions= **/node_modules/**,**/.next/**,**/out/**,**/coverage/**,**/public/**,**/assets/**,**/__test__/**,**/*.config.js,**/*.config.ts,**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
# sonar.scm.provider=git
sonar.projectName=SITOLAUT TERNAK
sonar.test=__test__
sonar.issue.ignore.multicriteria=tailwindAtRules
sonar.issue.ignore.multicriteria.tailwindAtRules.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.tailwindAtRules.resourceKey=**/globals.css